name: Busybox Make

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  Kernel_Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Dependencies
        run: |
          sudo -E apt update
          sudo -E apt -y install bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils
          sudo -E systemctl daemon-reload
          sudo -E apt autoremove
          sudo -E apt clean

      - name: Get BusyBox Source Code
        run: |
          wget www.busybox.net/downloads/busybox-1.37.0.tar.bz2
          tar -xvjf busybox-1.37.0.tar.bz2

      - name: Generate config file
        run: |
          cd busybox-1.37.0
          mv ./networking/tc.c ./
          make defconfig

      - name: Build Busybox
        run: |
          cd busybox-1.37.0
          make -j 16
          mkdir artifact
          make install CONFIG_PREFIX=./artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Result
          path: .busybox-1.37.0/artifact/*
