name: Linux Kernel Make

env:
  KERNEL : 6.15.4
  B_KERNEL : 6

on:
  workflow_dispatch: 

permissions:
  contents: write

jobs:

  Kernel_Build:
   runs-on: Ubuntu-latest
   steps:
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
          
      - name: Initialization environment
        run: |
          sudo -E apt update
          sudo -E apt -y full-upgrade
          sudo -E apt -y install bc binutils bison dwarves flex gcc git gnupg2 gzip libelf-dev libncurses5-dev libssl-dev make openssl pahole perl-base rsync tar xz-utils
          sudo -E systemctl daemon-reload
          sudo -E apt autoremove
          sudo -E apt clean
      
      - name: Get source code
        run: |
         wget https://cdn.kernel.org/pub/linux/kernel/v$B_KERNEL.x/linux-$KERNEL.tar.xz
         tar -xvf linux-$KERNEL.tar.xz

      - name: Generate config file
        run: |
         cp .config ./linux-$KERNEL

      - name: Build kernel
        run: |
         cd linux-$KERNEL
         make -j16

      - name: Prepare artifact
        run: |
          mkdir artifact
          cp ./linux-$KERNEL/arch/x86/boot/bzImage ./artifact/
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Image
          path: ./artifact/*
